#! /bin/bash

#stop any running polybar

killall -q polybar

#Wait untill all processes have been stopped

while pgrep -u $uid -x polybar >/dev/null;
 do sleep 1;
 done

#launcg bar

polybar example 



